spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.193.57:3306/VOA?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: haoyingkai0329
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8081